name: persistant_webview
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'



dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  webview_flutter: ^4.0.4
  url_launcher: ^6.1.9
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

 
